/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCoreRouteImport } from './routes/_app/core'
import { Route as AppDataRouteImport } from './routes/_app/data'
import { Route as AppEnvRouteImport } from './routes/_app/env'
import { Route as AppInnerRouteImport } from './routes/_app/inner'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppMemoriesRouteImport } from './routes/_app/memories'
import { Route as AppMemoryRouteImport } from './routes/_app/memory'
import { Route as AppPermissionsRouteImport } from './routes/_app/permissions'
import { Route as AppPlayRouteImport } from './routes/_app/play'
import { Route as AppSpaceRouteImport } from './routes/_app/space'
import { Route as AppSystemRouteImport } from './routes/_app/system'
import { Route as AppUsageRouteImport } from './routes/_app/usage'
import { Route as AppVoiceRouteImport } from './routes/_app/voice'
import { Route as AppWorldbookRouteImport } from './routes/_app/worldbook'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiHotRouteImport } from './routes/api/hot'
import { Route as ApiLyricsRouteImport } from './routes/api/lyrics'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiReadRouteImport } from './routes/api/read'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiWakeRouteImport } from './routes/api/wake'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as AppPlayIndexRouteImport } from './routes/_app/play.index'
import { Route as AppPlayAddRouteImport } from './routes/_app/play.add'
import { Route as AppPlayDaysRouteImport } from './routes/_app/play.days'
import { Route as AppPlayLearnRouteImport } from './routes/_app/play.learn'
import { Route as AppPlayListenRouteImport } from './routes/_app/play.listen'
import { Route as AppPlayPlayerRouteImport } from './routes/_app/play.player'
import { Route as AppPlayShiganRouteImport } from './routes/_app/play.shigan'
import { Route as AppPlaySpaceRouteImport } from './routes/_app/play.space'
import { Route as AppPlayTodoRouteImport } from './routes/_app/play.todo'
import { Route as AppToolsIndexRouteImport } from './routes/_app/tools/index'
import { Route as AppToolsDocsRouteImport } from './routes/_app/tools/docs'
import { Route as AppToolsHttpRouteImport } from './routes/_app/tools/http'
import { Route as AppToolsMcpRouteImport } from './routes/_app/tools/mcp'
import { Route as ApiPushKeyRouteImport } from './routes/api/push/key'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push/subscribe'
import { Route as AppPlayGamesIndexRouteImport } from './routes/_app/play.games.index'
import { Route as AppPlayGamesGobangRouteImport } from './routes/_app/play.games.gobang'
import { Route as AppPlayGamesTruthRouteImport } from './routes/_app/play.games.truth'
import { Route as AppPlayPluginsIndexRouteImport } from './routes/_app/play.plugins.index'
import { Route as AppPlayPluginsSlugRouteImport } from './routes/_app/play/plugins/$slug'
import { Route as AppPlayPluginsEditRouteImport } from './routes/_app/play/plugins/edit'
import { Route as AppPlayPluginsMemoryRouteImport } from './routes/_app/play/plugins/memory'
import { Route as AppPlayPluginsShiganRouteImport } from './routes/_app/play/plugins/shigan'
import { Route as AppPlayToolsIndexRouteImport } from './routes/_app/play.tools/index'
import { Route as AppPlayToolsAlarmsRouteImport } from './routes/_app/play.tools/alarms'
import { Route as AppPlayToolsTasksRouteImport } from './routes/_app/play.tools/tasks'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoreRoute = AppCoreRouteImport.update({
  id: '/core',
  path: '/core',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppRoute,
} as any)
const AppEnvRoute = AppEnvRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => AppRoute,
} as any)
const AppInnerRoute = AppInnerRouteImport.update({
  id: '/inner',
  path: '/inner',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoriesRoute = AppMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppPermissionsRoute = AppPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayRoute = AppPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AppRoute,
} as any)
const AppSpaceRoute = AppSpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppWorldbookRoute = AppWorldbookRouteImport.update({
  id: '/worldbook',
  path: '/worldbook',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHotRoute = ApiHotRouteImport.update({
  id: '/api/hot',
  path: '/api/hot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLyricsRoute = ApiLyricsRouteImport.update({
  id: '/api/lyrics',
  path: '/api/lyrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadRoute = ApiReadRouteImport.update({
  id: '/api/read',
  path: '/api/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWakeRoute = ApiWakeRouteImport.update({
  id: '/api/wake',
  path: '/api/wake',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPlayIndexRoute = AppPlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayAddRoute = AppPlayAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayDaysRoute = AppPlayDaysRouteImport.update({
  id: '/days',
  path: '/days',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayLearnRoute = AppPlayLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayListenRoute = AppPlayListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayPlayerRoute = AppPlayPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayShiganRoute = AppPlayShiganRouteImport.update({
  id: '/shigan',
  path: '/shigan',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlaySpaceRoute = AppPlaySpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayTodoRoute = AppPlayTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppToolsIndexRoute = AppToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsDocsRoute = AppToolsDocsRouteImport.update({
  id: '/tools/docs',
  path: '/tools/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsHttpRoute = AppToolsHttpRouteImport.update({
  id: '/tools/http',
  path: '/tools/http',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsMcpRoute = AppToolsMcpRouteImport.update({
  id: '/tools/mcp',
  path: '/tools/mcp',
  getParentRoute: () => AppRoute,
} as any)
const ApiPushKeyRoute = ApiPushKeyRouteImport.update({
  id: '/api/push/key',
  path: '/api/push/key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPlayGamesIndexRoute = AppPlayGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayGamesGobangRoute = AppPlayGamesGobangRouteImport.update({
  id: '/games/gobang',
  path: '/games/gobang',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayGamesTruthRoute = AppPlayGamesTruthRouteImport.update({
  id: '/games/truth',
  path: '/games/truth',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayPluginsIndexRoute = AppPlayPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayPluginsSlugRoute = AppPlayPluginsSlugRouteImport.update({
  id: '/plugins/$slug',
  path: '/plugins/$slug',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayPluginsEditRoute = AppPlayPluginsEditRouteImport.update({
  id: '/plugins/edit',
  path: '/plugins/edit',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayPluginsMemoryRoute = AppPlayPluginsMemoryRouteImport.update({
  id: '/plugins/memory',
  path: '/plugins/memory',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayPluginsShiganRoute = AppPlayPluginsShiganRouteImport.update({
  id: '/plugins/shigan',
  path: '/plugins/shigan',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayToolsIndexRoute = AppPlayToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayToolsAlarmsRoute = AppPlayToolsAlarmsRouteImport.update({
  id: '/tools/alarms',
  path: '/tools/alarms',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayToolsTasksRoute = AppPlayToolsTasksRouteImport.update({
  id: '/tools/tasks',
  path: '/tools/tasks',
  getParentRoute: () => AppPlayRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/core': typeof AppCoreRoute
  '/data': typeof AppDataRoute
  '/env': typeof AppEnvRoute
  '/inner': typeof AppInnerRoute
  '/me': typeof AppMeRoute
  '/memories': typeof AppMemoriesRoute
  '/memory': typeof AppMemoryRoute
  '/permissions': typeof AppPermissionsRoute
  '/play': typeof AppPlayRouteWithChildren
  '/space': typeof AppSpaceRoute
  '/system': typeof AppSystemRoute
  '/usage': typeof AppUsageRoute
  '/voice': typeof AppVoiceRoute
  '/worldbook': typeof AppWorldbookRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hot': typeof ApiHotRoute
  '/api/lyrics': typeof ApiLyricsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/read': typeof ApiReadRoute
  '/api/search': typeof ApiSearchRoute
  '/api/wake': typeof ApiWakeRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/play/add': typeof AppPlayAddRoute
  '/play/days': typeof AppPlayDaysRoute
  '/play/learn': typeof AppPlayLearnRoute
  '/play/listen': typeof AppPlayListenRoute
  '/play/player': typeof AppPlayPlayerRoute
  '/play/shigan': typeof AppPlayShiganRoute
  '/play/space': typeof AppPlaySpaceRoute
  '/play/todo': typeof AppPlayTodoRoute
  '/tools/docs': typeof AppToolsDocsRoute
  '/tools/http': typeof AppToolsHttpRoute
  '/tools/mcp': typeof AppToolsMcpRoute
  '/api/push/key': typeof ApiPushKeyRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/play/': typeof AppPlayIndexRoute
  '/tools/': typeof AppToolsIndexRoute
  '/play/games/gobang': typeof AppPlayGamesGobangRoute
  '/play/games/truth': typeof AppPlayGamesTruthRoute
  '/play/plugins/$slug': typeof AppPlayPluginsSlugRoute
  '/play/plugins/edit': typeof AppPlayPluginsEditRoute
  '/play/plugins/memory': typeof AppPlayPluginsMemoryRoute
  '/play/plugins/shigan': typeof AppPlayPluginsShiganRoute
  '/play/tools/alarms': typeof AppPlayToolsAlarmsRoute
  '/play/tools/tasks': typeof AppPlayToolsTasksRoute
  '/play/games/': typeof AppPlayGamesIndexRoute
  '/play/plugins/': typeof AppPlayPluginsIndexRoute
  '/play/tools/': typeof AppPlayToolsIndexRoute
}
export interface FileRoutesByTo {
  '/core': typeof AppCoreRoute
  '/data': typeof AppDataRoute
  '/env': typeof AppEnvRoute
  '/inner': typeof AppInnerRoute
  '/me': typeof AppMeRoute
  '/memories': typeof AppMemoriesRoute
  '/memory': typeof AppMemoryRoute
  '/permissions': typeof AppPermissionsRoute
  '/space': typeof AppSpaceRoute
  '/system': typeof AppSystemRoute
  '/usage': typeof AppUsageRoute
  '/voice': typeof AppVoiceRoute
  '/worldbook': typeof AppWorldbookRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hot': typeof ApiHotRoute
  '/api/lyrics': typeof ApiLyricsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/read': typeof ApiReadRoute
  '/api/search': typeof ApiSearchRoute
  '/api/wake': typeof ApiWakeRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/': typeof AppIndexRoute
  '/play/add': typeof AppPlayAddRoute
  '/play/days': typeof AppPlayDaysRoute
  '/play/learn': typeof AppPlayLearnRoute
  '/play/listen': typeof AppPlayListenRoute
  '/play/player': typeof AppPlayPlayerRoute
  '/play/shigan': typeof AppPlayShiganRoute
  '/play/space': typeof AppPlaySpaceRoute
  '/play/todo': typeof AppPlayTodoRoute
  '/tools/docs': typeof AppToolsDocsRoute
  '/tools/http': typeof AppToolsHttpRoute
  '/tools/mcp': typeof AppToolsMcpRoute
  '/api/push/key': typeof ApiPushKeyRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/play': typeof AppPlayIndexRoute
  '/tools': typeof AppToolsIndexRoute
  '/play/games/gobang': typeof AppPlayGamesGobangRoute
  '/play/games/truth': typeof AppPlayGamesTruthRoute
  '/play/plugins/$slug': typeof AppPlayPluginsSlugRoute
  '/play/plugins/edit': typeof AppPlayPluginsEditRoute
  '/play/plugins/memory': typeof AppPlayPluginsMemoryRoute
  '/play/plugins/shigan': typeof AppPlayPluginsShiganRoute
  '/play/tools/alarms': typeof AppPlayToolsAlarmsRoute
  '/play/tools/tasks': typeof AppPlayToolsTasksRoute
  '/play/games': typeof AppPlayGamesIndexRoute
  '/play/plugins': typeof AppPlayPluginsIndexRoute
  '/play/tools': typeof AppPlayToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/core': typeof AppCoreRoute
  '/_app/data': typeof AppDataRoute
  '/_app/env': typeof AppEnvRoute
  '/_app/inner': typeof AppInnerRoute
  '/_app/me': typeof AppMeRoute
  '/_app/memories': typeof AppMemoriesRoute
  '/_app/memory': typeof AppMemoryRoute
  '/_app/permissions': typeof AppPermissionsRoute
  '/_app/play': typeof AppPlayRouteWithChildren
  '/_app/space': typeof AppSpaceRoute
  '/_app/system': typeof AppSystemRoute
  '/_app/usage': typeof AppUsageRoute
  '/_app/voice': typeof AppVoiceRoute
  '/_app/worldbook': typeof AppWorldbookRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hot': typeof ApiHotRoute
  '/api/lyrics': typeof ApiLyricsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/read': typeof ApiReadRoute
  '/api/search': typeof ApiSearchRoute
  '/api/wake': typeof ApiWakeRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/_app/': typeof AppIndexRoute
  '/_app/play/add': typeof AppPlayAddRoute
  '/_app/play/days': typeof AppPlayDaysRoute
  '/_app/play/learn': typeof AppPlayLearnRoute
  '/_app/play/listen': typeof AppPlayListenRoute
  '/_app/play/player': typeof AppPlayPlayerRoute
  '/_app/play/shigan': typeof AppPlayShiganRoute
  '/_app/play/space': typeof AppPlaySpaceRoute
  '/_app/play/todo': typeof AppPlayTodoRoute
  '/_app/tools/docs': typeof AppToolsDocsRoute
  '/_app/tools/http': typeof AppToolsHttpRoute
  '/_app/tools/mcp': typeof AppToolsMcpRoute
  '/api/push/key': typeof ApiPushKeyRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/_app/play/': typeof AppPlayIndexRoute
  '/_app/tools/': typeof AppToolsIndexRoute
  '/_app/play/games/gobang': typeof AppPlayGamesGobangRoute
  '/_app/play/games/truth': typeof AppPlayGamesTruthRoute
  '/_app/play/plugins/$slug': typeof AppPlayPluginsSlugRoute
  '/_app/play/plugins/edit': typeof AppPlayPluginsEditRoute
  '/_app/play/plugins/memory': typeof AppPlayPluginsMemoryRoute
  '/_app/play/plugins/shigan': typeof AppPlayPluginsShiganRoute
  '/_app/play/tools/alarms': typeof AppPlayToolsAlarmsRoute
  '/_app/play/tools/tasks': typeof AppPlayToolsTasksRoute
  '/_app/play/games/': typeof AppPlayGamesIndexRoute
  '/_app/play/plugins/': typeof AppPlayPluginsIndexRoute
  '/_app/play/tools/': typeof AppPlayToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/core'
    | '/data'
    | '/env'
    | '/inner'
    | '/me'
    | '/memories'
    | '/memory'
    | '/permissions'
    | '/play'
    | '/space'
    | '/system'
    | '/usage'
    | '/voice'
    | '/worldbook'
    | '/api/chat'
    | '/api/hot'
    | '/api/lyrics'
    | '/api/models'
    | '/api/read'
    | '/api/search'
    | '/api/wake'
    | '/oauth/callback'
    | '/play/add'
    | '/play/days'
    | '/play/learn'
    | '/play/listen'
    | '/play/player'
    | '/play/shigan'
    | '/play/space'
    | '/play/todo'
    | '/tools/docs'
    | '/tools/http'
    | '/tools/mcp'
    | '/api/push/key'
    | '/api/push/subscribe'
    | '/play/'
    | '/tools/'
    | '/play/games/gobang'
    | '/play/games/truth'
    | '/play/plugins/$slug'
    | '/play/plugins/edit'
    | '/play/plugins/memory'
    | '/play/plugins/shigan'
    | '/play/tools/alarms'
    | '/play/tools/tasks'
    | '/play/games/'
    | '/play/plugins/'
    | '/play/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/core'
    | '/data'
    | '/env'
    | '/inner'
    | '/me'
    | '/memories'
    | '/memory'
    | '/permissions'
    | '/space'
    | '/system'
    | '/usage'
    | '/voice'
    | '/worldbook'
    | '/api/chat'
    | '/api/hot'
    | '/api/lyrics'
    | '/api/models'
    | '/api/read'
    | '/api/search'
    | '/api/wake'
    | '/oauth/callback'
    | '/'
    | '/play/add'
    | '/play/days'
    | '/play/learn'
    | '/play/listen'
    | '/play/player'
    | '/play/shigan'
    | '/play/space'
    | '/play/todo'
    | '/tools/docs'
    | '/tools/http'
    | '/tools/mcp'
    | '/api/push/key'
    | '/api/push/subscribe'
    | '/play'
    | '/tools'
    | '/play/games/gobang'
    | '/play/games/truth'
    | '/play/plugins/$slug'
    | '/play/plugins/edit'
    | '/play/plugins/memory'
    | '/play/plugins/shigan'
    | '/play/tools/alarms'
    | '/play/tools/tasks'
    | '/play/games'
    | '/play/plugins'
    | '/play/tools'
  id:
    | '__root__'
    | '/_app'
    | '/_app/core'
    | '/_app/data'
    | '/_app/env'
    | '/_app/inner'
    | '/_app/me'
    | '/_app/memories'
    | '/_app/memory'
    | '/_app/permissions'
    | '/_app/play'
    | '/_app/space'
    | '/_app/system'
    | '/_app/usage'
    | '/_app/voice'
    | '/_app/worldbook'
    | '/api/chat'
    | '/api/hot'
    | '/api/lyrics'
    | '/api/models'
    | '/api/read'
    | '/api/search'
    | '/api/wake'
    | '/oauth/callback'
    | '/_app/'
    | '/_app/play/add'
    | '/_app/play/days'
    | '/_app/play/learn'
    | '/_app/play/listen'
    | '/_app/play/player'
    | '/_app/play/shigan'
    | '/_app/play/space'
    | '/_app/play/todo'
    | '/_app/tools/docs'
    | '/_app/tools/http'
    | '/_app/tools/mcp'
    | '/api/push/key'
    | '/api/push/subscribe'
    | '/_app/play/'
    | '/_app/tools/'
    | '/_app/play/games/gobang'
    | '/_app/play/games/truth'
    | '/_app/play/plugins/$slug'
    | '/_app/play/plugins/edit'
    | '/_app/play/plugins/memory'
    | '/_app/play/plugins/shigan'
    | '/_app/play/tools/alarms'
    | '/_app/play/tools/tasks'
    | '/_app/play/games/'
    | '/_app/play/plugins/'
    | '/_app/play/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiHotRoute: typeof ApiHotRoute
  ApiLyricsRoute: typeof ApiLyricsRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiReadRoute: typeof ApiReadRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiWakeRoute: typeof ApiWakeRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  ApiPushKeyRoute: typeof ApiPushKeyRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/core': {
      id: '/_app/core'
      path: '/core'
      fullPath: '/core'
      preLoaderRoute: typeof AppCoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data': {
      id: '/_app/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/env': {
      id: '/_app/env'
      path: '/env'
      fullPath: '/env'
      preLoaderRoute: typeof AppEnvRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inner': {
      id: '/_app/inner'
      path: '/inner'
      fullPath: '/inner'
      preLoaderRoute: typeof AppInnerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memories': {
      id: '/_app/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof AppMemoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permissions': {
      id: '/_app/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AppPermissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play': {
      id: '/_app/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AppPlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/space': {
      id: '/_app/space'
      path: '/space'
      fullPath: '/space'
      preLoaderRoute: typeof AppSpaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voice': {
      id: '/_app/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/worldbook': {
      id: '/_app/worldbook'
      path: '/worldbook'
      fullPath: '/worldbook'
      preLoaderRoute: typeof AppWorldbookRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hot': {
      id: '/api/hot'
      path: '/api/hot'
      fullPath: '/api/hot'
      preLoaderRoute: typeof ApiHotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lyrics': {
      id: '/api/lyrics'
      path: '/api/lyrics'
      fullPath: '/api/lyrics'
      preLoaderRoute: typeof ApiLyricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/read': {
      id: '/api/read'
      path: '/api/read'
      fullPath: '/api/read'
      preLoaderRoute: typeof ApiReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wake': {
      id: '/api/wake'
      path: '/api/wake'
      fullPath: '/api/wake'
      preLoaderRoute: typeof ApiWakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/play/': {
      id: '/_app/play/'
      path: '/'
      fullPath: '/play/'
      preLoaderRoute: typeof AppPlayIndexRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/add': {
      id: '/_app/play/add'
      path: '/add'
      fullPath: '/play/add'
      preLoaderRoute: typeof AppPlayAddRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/days': {
      id: '/_app/play/days'
      path: '/days'
      fullPath: '/play/days'
      preLoaderRoute: typeof AppPlayDaysRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/learn': {
      id: '/_app/play/learn'
      path: '/learn'
      fullPath: '/play/learn'
      preLoaderRoute: typeof AppPlayLearnRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/listen': {
      id: '/_app/play/listen'
      path: '/listen'
      fullPath: '/play/listen'
      preLoaderRoute: typeof AppPlayListenRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/player': {
      id: '/_app/play/player'
      path: '/player'
      fullPath: '/play/player'
      preLoaderRoute: typeof AppPlayPlayerRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/shigan': {
      id: '/_app/play/shigan'
      path: '/shigan'
      fullPath: '/play/shigan'
      preLoaderRoute: typeof AppPlayShiganRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/space': {
      id: '/_app/play/space'
      path: '/space'
      fullPath: '/play/space'
      preLoaderRoute: typeof AppPlaySpaceRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/todo': {
      id: '/_app/play/todo'
      path: '/todo'
      fullPath: '/play/todo'
      preLoaderRoute: typeof AppPlayTodoRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/tools/': {
      id: '/_app/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AppToolsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/docs': {
      id: '/_app/tools/docs'
      path: '/tools/docs'
      fullPath: '/tools/docs'
      preLoaderRoute: typeof AppToolsDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/http': {
      id: '/_app/tools/http'
      path: '/tools/http'
      fullPath: '/tools/http'
      preLoaderRoute: typeof AppToolsHttpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools/mcp': {
      id: '/_app/tools/mcp'
      path: '/tools/mcp'
      fullPath: '/tools/mcp'
      preLoaderRoute: typeof AppToolsMcpRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/push/key': {
      id: '/api/push/key'
      path: '/api/push/key'
      fullPath: '/api/push/key'
      preLoaderRoute: typeof ApiPushKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/play/games/': {
      id: '/_app/play/games/'
      path: '/games'
      fullPath: '/play/games/'
      preLoaderRoute: typeof AppPlayGamesIndexRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/games/gobang': {
      id: '/_app/play/games/gobang'
      path: '/games/gobang'
      fullPath: '/play/games/gobang'
      preLoaderRoute: typeof AppPlayGamesGobangRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/games/truth': {
      id: '/_app/play/games/truth'
      path: '/games/truth'
      fullPath: '/play/games/truth'
      preLoaderRoute: typeof AppPlayGamesTruthRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/plugins/': {
      id: '/_app/play/plugins/'
      path: '/plugins'
      fullPath: '/play/plugins/'
      preLoaderRoute: typeof AppPlayPluginsIndexRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/plugins/$slug': {
      id: '/_app/play/plugins/$slug'
      path: '/plugins/$slug'
      fullPath: '/play/plugins/$slug'
      preLoaderRoute: typeof AppPlayPluginsSlugRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/plugins/edit': {
      id: '/_app/play/plugins/edit'
      path: '/plugins/edit'
      fullPath: '/play/plugins/edit'
      preLoaderRoute: typeof AppPlayPluginsEditRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/plugins/memory': {
      id: '/_app/play/plugins/memory'
      path: '/plugins/memory'
      fullPath: '/play/plugins/memory'
      preLoaderRoute: typeof AppPlayPluginsMemoryRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/plugins/shigan': {
      id: '/_app/play/plugins/shigan'
      path: '/plugins/shigan'
      fullPath: '/play/plugins/shigan'
      preLoaderRoute: typeof AppPlayPluginsShiganRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/tools/': {
      id: '/_app/play/tools/'
      path: '/tools'
      fullPath: '/play/tools/'
      preLoaderRoute: typeof AppPlayToolsIndexRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/tools/alarms': {
      id: '/_app/play/tools/alarms'
      path: '/tools/alarms'
      fullPath: '/play/tools/alarms'
      preLoaderRoute: typeof AppPlayToolsAlarmsRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/tools/tasks': {
      id: '/_app/play/tools/tasks'
      path: '/tools/tasks'
      fullPath: '/play/tools/tasks'
      preLoaderRoute: typeof AppPlayToolsTasksRouteImport
      parentRoute: typeof AppPlayRoute
    }
  }
}

interface AppPlayRouteChildren {
  AppPlayAddRoute: typeof AppPlayAddRoute
  AppPlayDaysRoute: typeof AppPlayDaysRoute
  AppPlayLearnRoute: typeof AppPlayLearnRoute
  AppPlayListenRoute: typeof AppPlayListenRoute
  AppPlayPlayerRoute: typeof AppPlayPlayerRoute
  AppPlayShiganRoute: typeof AppPlayShiganRoute
  AppPlaySpaceRoute: typeof AppPlaySpaceRoute
  AppPlayTodoRoute: typeof AppPlayTodoRoute
  AppPlayIndexRoute: typeof AppPlayIndexRoute
  AppPlayGamesGobangRoute: typeof AppPlayGamesGobangRoute
  AppPlayGamesTruthRoute: typeof AppPlayGamesTruthRoute
  AppPlayPluginsSlugRoute: typeof AppPlayPluginsSlugRoute
  AppPlayPluginsEditRoute: typeof AppPlayPluginsEditRoute
  AppPlayPluginsMemoryRoute: typeof AppPlayPluginsMemoryRoute
  AppPlayPluginsShiganRoute: typeof AppPlayPluginsShiganRoute
  AppPlayToolsAlarmsRoute: typeof AppPlayToolsAlarmsRoute
  AppPlayToolsTasksRoute: typeof AppPlayToolsTasksRoute
  AppPlayGamesIndexRoute: typeof AppPlayGamesIndexRoute
  AppPlayPluginsIndexRoute: typeof AppPlayPluginsIndexRoute
  AppPlayToolsIndexRoute: typeof AppPlayToolsIndexRoute
}

const AppPlayRouteChildren: AppPlayRouteChildren = {
  AppPlayAddRoute: AppPlayAddRoute,
  AppPlayDaysRoute: AppPlayDaysRoute,
  AppPlayLearnRoute: AppPlayLearnRoute,
  AppPlayListenRoute: AppPlayListenRoute,
  AppPlayPlayerRoute: AppPlayPlayerRoute,
  AppPlayShiganRoute: AppPlayShiganRoute,
  AppPlaySpaceRoute: AppPlaySpaceRoute,
  AppPlayTodoRoute: AppPlayTodoRoute,
  AppPlayIndexRoute: AppPlayIndexRoute,
  AppPlayGamesGobangRoute: AppPlayGamesGobangRoute,
  AppPlayGamesTruthRoute: AppPlayGamesTruthRoute,
  AppPlayPluginsSlugRoute: AppPlayPluginsSlugRoute,
  AppPlayPluginsEditRoute: AppPlayPluginsEditRoute,
  AppPlayPluginsMemoryRoute: AppPlayPluginsMemoryRoute,
  AppPlayPluginsShiganRoute: AppPlayPluginsShiganRoute,
  AppPlayToolsAlarmsRoute: AppPlayToolsAlarmsRoute,
  AppPlayToolsTasksRoute: AppPlayToolsTasksRoute,
  AppPlayGamesIndexRoute: AppPlayGamesIndexRoute,
  AppPlayPluginsIndexRoute: AppPlayPluginsIndexRoute,
  AppPlayToolsIndexRoute: AppPlayToolsIndexRoute,
}

const AppPlayRouteWithChildren =
  AppPlayRoute._addFileChildren(AppPlayRouteChildren)

interface AppRouteChildren {
  AppCoreRoute: typeof AppCoreRoute
  AppDataRoute: typeof AppDataRoute
  AppEnvRoute: typeof AppEnvRoute
  AppInnerRoute: typeof AppInnerRoute
  AppMeRoute: typeof AppMeRoute
  AppMemoriesRoute: typeof AppMemoriesRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppPermissionsRoute: typeof AppPermissionsRoute
  AppPlayRoute: typeof AppPlayRouteWithChildren
  AppSpaceRoute: typeof AppSpaceRoute
  AppSystemRoute: typeof AppSystemRoute
  AppUsageRoute: typeof AppUsageRoute
  AppVoiceRoute: typeof AppVoiceRoute
  AppWorldbookRoute: typeof AppWorldbookRoute
  AppIndexRoute: typeof AppIndexRoute
  AppToolsDocsRoute: typeof AppToolsDocsRoute
  AppToolsHttpRoute: typeof AppToolsHttpRoute
  AppToolsMcpRoute: typeof AppToolsMcpRoute
  AppToolsIndexRoute: typeof AppToolsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoreRoute: AppCoreRoute,
  AppDataRoute: AppDataRoute,
  AppEnvRoute: AppEnvRoute,
  AppInnerRoute: AppInnerRoute,
  AppMeRoute: AppMeRoute,
  AppMemoriesRoute: AppMemoriesRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppPermissionsRoute: AppPermissionsRoute,
  AppPlayRoute: AppPlayRouteWithChildren,
  AppSpaceRoute: AppSpaceRoute,
  AppSystemRoute: AppSystemRoute,
  AppUsageRoute: AppUsageRoute,
  AppVoiceRoute: AppVoiceRoute,
  AppWorldbookRoute: AppWorldbookRoute,
  AppIndexRoute: AppIndexRoute,
  AppToolsDocsRoute: AppToolsDocsRoute,
  AppToolsHttpRoute: AppToolsHttpRoute,
  AppToolsMcpRoute: AppToolsMcpRoute,
  AppToolsIndexRoute: AppToolsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiHotRoute: ApiHotRoute,
  ApiLyricsRoute: ApiLyricsRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiReadRoute: ApiReadRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiWakeRoute: ApiWakeRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  ApiPushKeyRoute: ApiPushKeyRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
