/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppEnvRouteImport } from './routes/_app/env'
import { Route as AppMeRouteImport } from './routes/_app/me'
import { Route as AppMemoryRouteImport } from './routes/_app/memory'
import { Route as AppPermissionsRouteImport } from './routes/_app/permissions'
import { Route as AppPlayRouteImport } from './routes/_app/play'
import { Route as AppToolsRouteImport } from './routes/_app/tools'
import { Route as AppVoiceRouteImport } from './routes/_app/voice'
import { Route as AppWorkspaceRouteImport } from './routes/_app/workspace'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiLyricsRouteImport } from './routes/api/lyrics'
import { Route as ApiWorkspaceRouteImport } from './routes/api/workspace'
import { Route as AppPlayIndexRouteImport } from './routes/_app/play.index'
import { Route as AppPlayAddRouteImport } from './routes/_app/play.add'
import { Route as AppPlayDaysRouteImport } from './routes/_app/play.days'
import { Route as AppPlayGobangRouteImport } from './routes/_app/play.gobang'
import { Route as AppPlayLearnRouteImport } from './routes/_app/play.learn'
import { Route as AppPlayListenRouteImport } from './routes/_app/play.listen'
import { Route as AppPlayPlayerRouteImport } from './routes/_app/play.player'
import { Route as AppPlayShiganRouteImport } from './routes/_app/play.shigan'
import { Route as AppPlaySpaceRouteImport } from './routes/_app/play.space'
import { Route as AppPlayTodoRouteImport } from './routes/_app/play.todo'
import { Route as AppPlayToolsRouteImport } from './routes/_app/play.tools'
import { Route as AppPlayTruthRouteImport } from './routes/_app/play.truth'
import { Route as ApiPushKeyRouteImport } from './routes/api/push/key'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push/subscribe'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEnvRoute = AppEnvRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppPermissionsRoute = AppPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppRoute,
} as any)
const AppPlayRoute = AppPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLyricsRoute = ApiLyricsRouteImport.update({
  id: '/api/lyrics',
  path: '/api/lyrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPlayIndexRoute = AppPlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayAddRoute = AppPlayAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayDaysRoute = AppPlayDaysRouteImport.update({
  id: '/days',
  path: '/days',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayGobangRoute = AppPlayGobangRouteImport.update({
  id: '/gobang',
  path: '/gobang',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayLearnRoute = AppPlayLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayListenRoute = AppPlayListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayPlayerRoute = AppPlayPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayShiganRoute = AppPlayShiganRouteImport.update({
  id: '/shigan',
  path: '/shigan',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlaySpaceRoute = AppPlaySpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayTodoRoute = AppPlayTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayToolsRoute = AppPlayToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppPlayRoute,
} as any)
const AppPlayTruthRoute = AppPlayTruthRouteImport.update({
  id: '/truth',
  path: '/truth',
  getParentRoute: () => AppPlayRoute,
} as any)
const ApiPushKeyRoute = ApiPushKeyRouteImport.update({
  id: '/api/push/key',
  path: '/api/push/key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/env': typeof AppEnvRoute
  '/me': typeof AppMeRoute
  '/memory': typeof AppMemoryRoute
  '/permissions': typeof AppPermissionsRoute
  '/play': typeof AppPlayRouteWithChildren
  '/tools': typeof AppToolsRoute
  '/voice': typeof AppVoiceRoute
  '/workspace': typeof AppWorkspaceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/lyrics': typeof ApiLyricsRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/play/add': typeof AppPlayAddRoute
  '/play/days': typeof AppPlayDaysRoute
  '/play/gobang': typeof AppPlayGobangRoute
  '/play/learn': typeof AppPlayLearnRoute
  '/play/listen': typeof AppPlayListenRoute
  '/play/player': typeof AppPlayPlayerRoute
  '/play/shigan': typeof AppPlayShiganRoute
  '/play/space': typeof AppPlaySpaceRoute
  '/play/todo': typeof AppPlayTodoRoute
  '/play/tools': typeof AppPlayToolsRoute
  '/play/truth': typeof AppPlayTruthRoute
  '/api/push/key': typeof ApiPushKeyRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/play/': typeof AppPlayIndexRoute
}
export interface FileRoutesByTo {
  '/env': typeof AppEnvRoute
  '/me': typeof AppMeRoute
  '/memory': typeof AppMemoryRoute
  '/permissions': typeof AppPermissionsRoute
  '/tools': typeof AppToolsRoute
  '/voice': typeof AppVoiceRoute
  '/workspace': typeof AppWorkspaceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/lyrics': typeof ApiLyricsRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/': typeof AppIndexRoute
  '/play/add': typeof AppPlayAddRoute
  '/play/days': typeof AppPlayDaysRoute
  '/play/gobang': typeof AppPlayGobangRoute
  '/play/learn': typeof AppPlayLearnRoute
  '/play/listen': typeof AppPlayListenRoute
  '/play/player': typeof AppPlayPlayerRoute
  '/play/shigan': typeof AppPlayShiganRoute
  '/play/space': typeof AppPlaySpaceRoute
  '/play/todo': typeof AppPlayTodoRoute
  '/play/tools': typeof AppPlayToolsRoute
  '/play/truth': typeof AppPlayTruthRoute
  '/api/push/key': typeof ApiPushKeyRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/play': typeof AppPlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/env': typeof AppEnvRoute
  '/_app/me': typeof AppMeRoute
  '/_app/memory': typeof AppMemoryRoute
  '/_app/permissions': typeof AppPermissionsRoute
  '/_app/play': typeof AppPlayRouteWithChildren
  '/_app/tools': typeof AppToolsRoute
  '/_app/voice': typeof AppVoiceRoute
  '/_app/workspace': typeof AppWorkspaceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/lyrics': typeof ApiLyricsRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/_app/': typeof AppIndexRoute
  '/_app/play/add': typeof AppPlayAddRoute
  '/_app/play/days': typeof AppPlayDaysRoute
  '/_app/play/gobang': typeof AppPlayGobangRoute
  '/_app/play/learn': typeof AppPlayLearnRoute
  '/_app/play/listen': typeof AppPlayListenRoute
  '/_app/play/player': typeof AppPlayPlayerRoute
  '/_app/play/shigan': typeof AppPlayShiganRoute
  '/_app/play/space': typeof AppPlaySpaceRoute
  '/_app/play/todo': typeof AppPlayTodoRoute
  '/_app/play/tools': typeof AppPlayToolsRoute
  '/_app/play/truth': typeof AppPlayTruthRoute
  '/api/push/key': typeof ApiPushKeyRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/_app/play/': typeof AppPlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/env'
    | '/me'
    | '/memory'
    | '/permissions'
    | '/play'
    | '/tools'
    | '/voice'
    | '/workspace'
    | '/api/chat'
    | '/api/lyrics'
    | '/api/workspace'
    | '/play/add'
    | '/play/days'
    | '/play/gobang'
    | '/play/learn'
    | '/play/listen'
    | '/play/player'
    | '/play/shigan'
    | '/play/space'
    | '/play/todo'
    | '/play/tools'
    | '/play/truth'
    | '/api/push/key'
    | '/api/push/subscribe'
    | '/play/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/env'
    | '/me'
    | '/memory'
    | '/permissions'
    | '/tools'
    | '/voice'
    | '/workspace'
    | '/api/chat'
    | '/api/lyrics'
    | '/api/workspace'
    | '/'
    | '/play/add'
    | '/play/days'
    | '/play/gobang'
    | '/play/learn'
    | '/play/listen'
    | '/play/player'
    | '/play/shigan'
    | '/play/space'
    | '/play/todo'
    | '/play/tools'
    | '/play/truth'
    | '/api/push/key'
    | '/api/push/subscribe'
    | '/play'
  id:
    | '__root__'
    | '/_app'
    | '/_app/env'
    | '/_app/me'
    | '/_app/memory'
    | '/_app/permissions'
    | '/_app/play'
    | '/_app/tools'
    | '/_app/voice'
    | '/_app/workspace'
    | '/api/chat'
    | '/api/lyrics'
    | '/api/workspace'
    | '/_app/'
    | '/_app/play/add'
    | '/_app/play/days'
    | '/_app/play/gobang'
    | '/_app/play/learn'
    | '/_app/play/listen'
    | '/_app/play/player'
    | '/_app/play/shigan'
    | '/_app/play/space'
    | '/_app/play/todo'
    | '/_app/play/tools'
    | '/_app/play/truth'
    | '/api/push/key'
    | '/api/push/subscribe'
    | '/_app/play/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiLyricsRoute: typeof ApiLyricsRoute
  ApiWorkspaceRoute: typeof ApiWorkspaceRoute
  ApiPushKeyRoute: typeof ApiPushKeyRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/env': {
      id: '/_app/env'
      path: '/env'
      fullPath: '/env'
      preLoaderRoute: typeof AppEnvRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/permissions': {
      id: '/_app/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AppPermissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/play': {
      id: '/_app/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AppPlayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools': {
      id: '/_app/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/voice': {
      id: '/_app/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace': {
      id: '/_app/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lyrics': {
      id: '/api/lyrics'
      path: '/api/lyrics'
      fullPath: '/api/lyrics'
      preLoaderRoute: typeof ApiLyricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/play/': {
      id: '/_app/play/'
      path: '/'
      fullPath: '/play/'
      preLoaderRoute: typeof AppPlayIndexRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/add': {
      id: '/_app/play/add'
      path: '/add'
      fullPath: '/play/add'
      preLoaderRoute: typeof AppPlayAddRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/days': {
      id: '/_app/play/days'
      path: '/days'
      fullPath: '/play/days'
      preLoaderRoute: typeof AppPlayDaysRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/gobang': {
      id: '/_app/play/gobang'
      path: '/gobang'
      fullPath: '/play/gobang'
      preLoaderRoute: typeof AppPlayGobangRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/learn': {
      id: '/_app/play/learn'
      path: '/learn'
      fullPath: '/play/learn'
      preLoaderRoute: typeof AppPlayLearnRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/listen': {
      id: '/_app/play/listen'
      path: '/listen'
      fullPath: '/play/listen'
      preLoaderRoute: typeof AppPlayListenRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/player': {
      id: '/_app/play/player'
      path: '/player'
      fullPath: '/play/player'
      preLoaderRoute: typeof AppPlayPlayerRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/shigan': {
      id: '/_app/play/shigan'
      path: '/shigan'
      fullPath: '/play/shigan'
      preLoaderRoute: typeof AppPlayShiganRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/space': {
      id: '/_app/play/space'
      path: '/space'
      fullPath: '/play/space'
      preLoaderRoute: typeof AppPlaySpaceRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/todo': {
      id: '/_app/play/todo'
      path: '/todo'
      fullPath: '/play/todo'
      preLoaderRoute: typeof AppPlayTodoRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/tools': {
      id: '/_app/play/tools'
      path: '/tools'
      fullPath: '/play/tools'
      preLoaderRoute: typeof AppPlayToolsRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/_app/play/truth': {
      id: '/_app/play/truth'
      path: '/truth'
      fullPath: '/play/truth'
      preLoaderRoute: typeof AppPlayTruthRouteImport
      parentRoute: typeof AppPlayRoute
    }
    '/api/push/key': {
      id: '/api/push/key'
      path: '/api/push/key'
      fullPath: '/api/push/key'
      preLoaderRoute: typeof ApiPushKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppPlayRouteChildren {
  AppPlayAddRoute: typeof AppPlayAddRoute
  AppPlayDaysRoute: typeof AppPlayDaysRoute
  AppPlayGobangRoute: typeof AppPlayGobangRoute
  AppPlayLearnRoute: typeof AppPlayLearnRoute
  AppPlayListenRoute: typeof AppPlayListenRoute
  AppPlayPlayerRoute: typeof AppPlayPlayerRoute
  AppPlayShiganRoute: typeof AppPlayShiganRoute
  AppPlaySpaceRoute: typeof AppPlaySpaceRoute
  AppPlayTodoRoute: typeof AppPlayTodoRoute
  AppPlayToolsRoute: typeof AppPlayToolsRoute
  AppPlayTruthRoute: typeof AppPlayTruthRoute
  AppPlayIndexRoute: typeof AppPlayIndexRoute
}

const AppPlayRouteChildren: AppPlayRouteChildren = {
  AppPlayAddRoute: AppPlayAddRoute,
  AppPlayDaysRoute: AppPlayDaysRoute,
  AppPlayGobangRoute: AppPlayGobangRoute,
  AppPlayLearnRoute: AppPlayLearnRoute,
  AppPlayListenRoute: AppPlayListenRoute,
  AppPlayPlayerRoute: AppPlayPlayerRoute,
  AppPlayShiganRoute: AppPlayShiganRoute,
  AppPlaySpaceRoute: AppPlaySpaceRoute,
  AppPlayTodoRoute: AppPlayTodoRoute,
  AppPlayToolsRoute: AppPlayToolsRoute,
  AppPlayTruthRoute: AppPlayTruthRoute,
  AppPlayIndexRoute: AppPlayIndexRoute,
}

const AppPlayRouteWithChildren =
  AppPlayRoute._addFileChildren(AppPlayRouteChildren)

interface AppRouteChildren {
  AppEnvRoute: typeof AppEnvRoute
  AppMeRoute: typeof AppMeRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppPermissionsRoute: typeof AppPermissionsRoute
  AppPlayRoute: typeof AppPlayRouteWithChildren
  AppToolsRoute: typeof AppToolsRoute
  AppVoiceRoute: typeof AppVoiceRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEnvRoute: AppEnvRoute,
  AppMeRoute: AppMeRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppPermissionsRoute: AppPermissionsRoute,
  AppPlayRoute: AppPlayRouteWithChildren,
  AppToolsRoute: AppToolsRoute,
  AppVoiceRoute: AppVoiceRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiLyricsRoute: ApiLyricsRoute,
  ApiWorkspaceRoute: ApiWorkspaceRoute,
  ApiPushKeyRoute: ApiPushKeyRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
